Repository KyoriPowered/adventure-text-minimessage, pull requests merged in 2021-09, with the labels that each got.

#148 Fix colour and c not being parsed the same way as color
  src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/ColorTransformation.java
  src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java
Labels: type: bug

#145 chore: Remove markdown support
  src/main/java/net/kyori/adventure/text/minimessage/MiniMessage.java
  src/main/java/net/kyori/adventure/text/minimessage/MiniMessageImpl.java
  src/main/java/net/kyori/adventure/text/minimessage/markdown/DiscordFlavor.java
  src/main/java/net/kyori/adventure/text/minimessage/markdown/GithubFlavor.java
  src/main/java/net/kyori/adventure/text/minimessage/markdown/LegacyFlavor.java
  src/main/java/net/kyori/adventure/text/minimessage/markdown/MarkdownFlavor.java
  src/main/java/net/kyori/adventure/text/minimessage/markdown/MiniMarkdownParser.java
  src/main/java/net/kyori/adventure/text/minimessage/markdown/package-info.java
  src/test/java/net/kyori/adventure/text/minimessage/MiniMessageTest.java
  src/test/java/net/kyori/adventure/text/minimessage/markdown/MiniMarkdownParserTest.java
Labels: area: markdown

#155 Improve font transformation control flow
  src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/FontTransformation.java
  src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java
Labels: type: enhancement

#159 attempt to tackle #137
  src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/GradientTransformation.java
  src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/RainbowTransformation.java
  src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java
Labels: type: bug

#152 Reversed Rainbow
  src/main/java/net/kyori/adventure/text/minimessage/Tokens.java
  src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/RainbowTransformation.java
  src/test/java/net/kyori/adventure/text/minimessage/MiniMessageParserTest.java
Labels: type: enhancement
